#!/usr/bin/env python3
"""zyrthi build 适配器 - ESP-IDF"""

import json, os, shutil, subprocess, sys
from pathlib import Path

CHIP_TOOLCHAIN = {
    'esp32': 'xtensa', 'esp32s2': 'xtensa', 'esp32s3': 'xtensa',
    'esp32c3': 'riscv32', 'esp32c6': 'riscv32', 'esp32h2': 'riscv32',
}

CHIP_COMPILER = {
    'esp32': 'xtensa-esp32-elf', 'esp32s2': 'xtensa-esp32s2-elf', 'esp32s3': 'xtensa-esp32s3-elf',
    'esp32c3': 'riscv32-esp-elf', 'esp32c6': 'riscv32-esp-elf', 'esp32h2': 'riscv32-esp-elf',
}

def generate_cmakelists():
    return '''cmake_minimum_required(VERSION 3.16)
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(zyrthi-app C)
'''

def generate_component_cmakelists(src_files):
    # zyrthi 标准入口适配：注册所有源文件
    srcs = ' '.join(f'"{f}"' for f in src_files)
    return f'idf_component_register(SRCS {srcs} INCLUDE_DIRS ".")\n'

def generate_entry_wrapper():
    # zyrthi 标准入口包装器：ESP-IDF app_main 调用用户 main
    return '''// zyrthi ESP-IDF entry wrapper
// Auto-generated by zyrthi build system
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

extern int main(void);

void app_main(void) {
    ESP_LOGI("zyrthi", "Starting application...");
    main();
}
'''

def generate_sdkconfig(chip):
    return f'''CONFIG_IDF_TARGET="{chip}"
CONFIG_FREERTOS_HZ=1000
CONFIG_COMPILER_OPTIMIZATION_SIZE=y
CONFIG_ESP_TASK_WDT=n
CONFIG_LOG_DEFAULT_LEVEL_INFO=y
CONFIG_BT_ENABLED=n
CONFIG_ESP_WIFI_ENABLED=n
CONFIG_MQTT_ENABLED=n
CONFIG_HEAP_TLSF=n
'''

def build(req):
    chip = req.get('chip', 'esp32')
    tools_dir = Path(os.environ.get('ZYRTHI_TOOLS_DIR', '/opt/tools'))
    
    project_dir = Path('/src')
    main_dir = project_dir / 'main'
    main_dir.mkdir(exist_ok=True)
    
    # 清理旧的目标配置（切换芯片时）
    sdkconfig = project_dir / 'sdkconfig'
    sdkconfig_defaults = project_dir / 'sdkconfig.defaults'
    build_dir = project_dir / 'build'
    
    if sdkconfig.exists():
        # 读取当前目标
        content = sdkconfig.read_text()
        if f'CONFIG_IDF_TARGET="{chip}"' not in content:
            print(f"切换目标芯片，清理旧配置...", file=sys.stderr)
            # 清理 sdkconfig 和 build 目录
            sdkconfig.unlink()
            if build_dir.exists():
                shutil.rmtree(build_dir)
    
    # 递归查找所有源文件并移动到 main 目录
    for ext in ['*.c', '*.cpp', '*.h']:
        for f in project_dir.rglob(ext):
            if f.parent != main_dir:
                shutil.copy(str(f), str(main_dir / f.name))
    
    # 复制依赖目录的头文件和源文件
    deps_dir = project_dir / '.dehub' / 'deps'
    if deps_dir.exists():
        for pkg_dir in deps_dir.rglob('0.1.0'):
            # 复制 include 目录
            include_dir = pkg_dir / 'include'
            if include_dir.exists():
                for f in include_dir.rglob('*.h'):
                    rel_path = f.relative_to(include_dir)
                    dest = main_dir / rel_path
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy(str(f), str(dest))
            # 复制 src 目录
            src_dir = pkg_dir / 'src'
            if src_dir.exists():
                for f in src_dir.rglob('*.c'):
                    shutil.copy(str(f), str(main_dir / f.name))
    
    # 生成 zyrthi 标准入口包装器
    (main_dir / 'entry_wrapper.c').write_text(generate_entry_wrapper())
    
    # 收集所有源文件
    src_files = sorted([f.name for f in main_dir.glob('*.c')])
    
    (project_dir / 'CMakeLists.txt').write_text(generate_cmakelists())
    (main_dir / 'CMakeLists.txt').write_text(generate_component_cmakelists(src_files))
    (project_dir / 'sdkconfig.defaults').write_text(generate_sdkconfig(chip))
    
    # 设置环境
    env = os.environ.copy()
    # IDF 解压到 tools_dir/sdk 目录
    idf_path = tools_dir / 'sdk'
    python_env = tools_dir / 'python-env'
    
    toolchain_arch = CHIP_TOOLCHAIN.get(chip, 'xtensa')
    toolchain_name = f'{toolchain_arch}-esp-elf'
    
    # 查找实际工具链目录（处理多种目录结构）
    actual_toolchain = None
    search_paths = [
        # 缓存目录结构：直接在 tools_dir 下（无 toolchain 子目录）
        tools_dir / toolchain_name,
        # 镜像内解压结构：toolchain/riscv32-esp-elf/riscv32-esp-elf/bin/
        tools_dir / 'toolchain' / toolchain_name / toolchain_name,
        # 标准结构：toolchain/riscv32-esp-elf/bin/
        tools_dir / 'toolchain' / toolchain_name,
        # 原始结构：toolchain/riscv32/riscv32-esp-elf/bin/
        tools_dir / 'toolchain' / toolchain_arch / toolchain_name,
    ]
    for possible in search_paths:
        if possible.exists() and (possible / 'bin').exists():
            actual_toolchain = possible
            break
    
    toolchain_base = tools_dir / 'toolchain' if actual_toolchain else tools_dir
    
    if not actual_toolchain:
        return {'success': False, 'error': f'工具链目录结构错误: {toolchain_base}'}
    
    toolchain_bin = actual_toolchain / 'bin'
    compiler_prefix = CHIP_COMPILER.get(chip, 'xtensa-esp32-elf')
    
    env['CC'] = str(toolchain_bin / f'{compiler_prefix}-gcc')
    env['CXX'] = str(toolchain_bin / f'{compiler_prefix}-g++')
    env['ASM'] = str(toolchain_bin / f'{compiler_prefix}-gcc')
    
    env['IDF_PATH'] = str(idf_path)
    env['IDF_PYTHON_ENV_PATH'] = str(python_env)
    env['IDF_SKIP_CHECK_SUBMODULES'] = '1'
    env['IDF_COMPONENT_MANAGER'] = '0'
    env['IDF_TARGET'] = chip
    
    env['PATH'] = f"{toolchain_bin}:{python_env / 'bin'}:{env.get('PATH', '')}"
    
    idf_py = idf_path / 'tools' / 'idf.py'
    
    print(f"编译: {chip}", file=sys.stderr)
    print(f"工具链: {actual_toolchain}", file=sys.stderr)
    result = subprocess.run(
        ['python3', str(idf_py), 'build'],
        cwd=project_dir, env=env, capture_output=True, text=True
    )
    
    if result.returncode != 0:
        return {'success': False, 'error': result.stderr[-2000:] if result.stderr else result.stdout[-2000:]}
    
    elf = project_dir / 'build' / 'zyrthi-app.elf'
    if not elf.exists():
        for f in (project_dir / 'build').glob('*.elf'):
            elf = f
            break
    
    return {'success': True, 'binary': str(elf), 'size': elf.stat().st_size} if elf.exists() else {'success': False, 'error': 'ELF 未生成'}

if __name__ == '__main__':
    try:
        print(json.dumps(build(json.load(sys.stdin))))
    except Exception as e:
        print(json.dumps({'success': False, 'error': str(e)}))
        sys.exit(1)